#pragma once

#include "targetver.h"
#include <windows.h>
#include <iostream>
#include <psapi.h>
#include <string>
#include <algorithm>
#include <stdio.h>
#include <tchar.h>
#include <stdlib.h>
#include <cstdlib>
#include <winsock.h>
#include <vector>
#include <sstream>
#include <vector>
#include "player.h"
#include "localplayer.h"
#include "rand_char.h"
#include "game.h"
#include "cheat.h"
#include "vector2.h"
#include "vector3.h"
#include "scatter_string.h"
#include "decrypt_string.h"
#include "vector2.h"
#include "Console.h"
#include "ESP.h"
#include "Cheat.h"
#include <string>